# Copyright (c) 2018-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2018-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the LICENSE file.

# Configuration for the native Dependabot integration.
#
# References:
#   1. https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
#   2. https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-dependabot-version-updates
#   3. https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/about-dependabot-security-updates
#   4. https://github.com/features#features-security

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "arcticicestudio"
      - "svengreb"
    labels:
      - "scope-quality"
      - "scope-security"
      - "target-base"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      # Check all explicitly defined dependencies.
      - dependency-type: "direct"
    reviewers:
      - "arcticicestudio"
      - "svengreb"
    labels:
      - "scope-quality"
      - "scope-security"
      - "target-base"
